"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { Check, ChevronDown, Languages } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { cn } from "@/lib/utils";

const STORAGE_KEY = "happyboat-language";

const LANGUAGE_OPTIONS = [
  { value: "en", label: "English" },
  { value: "km", label: "ខ្មែរ" },
];

const DICTIONARY = {
  en: {
    addToCart: "Add to cart",
    add: "Add",
    addNewMenu: "Add New Menu",
    addDishes: "Add dishes to get started",
    addedToCart: "added to cart.",
    addedToCartTitle: "Added to cart",
    addExtras: "Add Extras",
    accept: "Accept",
    acceptAll: "Accept all",
    acceptedPreparing: "Accepted",
    addons: "Add-ons",
    allPrices: "All prices",
    allPayments: "All payments",
    allCategories: "All categories",
    allDates: "All dates",
    allStatuses: "All statuses",
    allTimes: "All times",
    alert: "Alert",
    alertStaff: "Alert staff",
    amountToPay: "Amount to pay",
    analytics: "Analytics",
    analyticsLoadFailed: "Analytics failed to load",
    accounts: "Accounts",
    accountDeactivated: "Account deactivated",
    accountDeactivateFailed: "Failed to deactivate account",
    accountCreateFailed: "Failed to create account",
    accountLoadFailed: "Failed to load accounts",
    appLanguage: "App language",
    active: "active",
    activeOrders: "Active orders",
    accessToken: "Access token",
    admin: "Admin",
    adminAccountCreated: "Admin account created successfully",
    adminAccounts: "Admin Accounts",
    awaitingPayment: "Payment",
    averageOrder: "Average Order",
    apply: "Apply",
    available: "Available",
    autoAcceptOn: "Auto-Accept ON",
    autoAcceptKitchenHint: "New paid items are accepted automatically.",
    back: "Back",
    cancel: "Cancel",
    cancelled: "Cancelled",
    cancelPayment: "Cancel payment",
    cartItemCount: "{count} items",
    capacity: "Capacity",
    callStaff: "Call staff",
    callingStaff: "Calling...",
    callStaffAlreadySent: "Staff is already on the way.",
    callStaffFailed: "Could not call staff.",
    callStaffRequests: "Call staff requests",
    callStaffSent: "Staff has been called.",
    callStaffSentShort: "Staff called",
    category: "Category",
    categories: "Categories",
    categoryCreated: "Category created.",
    categoryDeleted: "Category deleted.",
    categoryDeleteFailed: "Category delete failed",
    categoryHasItems: "Delete is available only after moving or deleting this category's menu items.",
    categoryItemCount: "{count} items",
    categoryName: "Category name",
    categoryOrder: "Order",
    categorySaveFailed: "Category save failed",
    categorySlug: "Slug",
    categoryUpdated: "Category updated.",
    changeLanguage: "Change language",
    changeMerchantDetails: "Change Merchant Details",
    checkYourEmail: "Check your email",
    checkPaymentStatus: "Check payment status",
    generateNewQr: "Generate new QR",
    checking: "Checking",
    checkingPayment: "Checking payment...",
    checkingPromoCode: "Checking promo code...",
    chooseSizeLevel: "Choose Size Level",
    bakongAccessToken: "Bakong access token",
    bakongEmail: "Bakong registered email",
    bakongPaymentSettings: "Bakong payment settings for new QR payments.",
    beepOnly: "Beep only",
    browserVoice: "Browser",
    clearFilters: "Clear filters",
    complete: "Complete",
    completeAll: "Complete all",
    completed: "Completed",
    confirmAcceptAll: "Accept {count} pending {item} item(s)?",
    confirmCompleteAll: "Complete {count} accepted {item} item(s)?",
    confirmCancelOrder: "Cancel this order?",
    confirmCancelPayment: "Cancel this payment? The order will be cancelled on this device.",
    confirmDeleteCategory: "Delete this category?",
    confirmPaid: "I already received Bakong payment",
    confirmPaymentPrompt: "Confirm this payment as PAID? Use this only when you already received the Bakong money.",
    confirming: "Confirming...",
    create: "Create",
    createAdmin: "Create Admin",
    codeExpiresIn: "Code expires in {time}",
    confirmDeactivateAccount: "Deactivate {username}?",
    customerAlertFailed: "Could not alert staff.",
    customerAlertSent: "Staff has been alerted.",
    customerAlertSentShort: "Staff alerted",
    customerWaitingVoice: "Customer has waited ten minutes",
    dailyRevenue: "Daily Revenue",
    dashboardTitle: "HappyBoat Dashboard",
    dashboardSubtitle: "SuperAdmin and admin access",
    close: "Close",
    closeCart: "Close cart",
    dashboard: "Dashboard",
    defaultLabel: "Default",
    defaultCurrency: "Default currency",
    decrease: "Decrease",
    deactivate: "Deactivate",
    deleteCategory: "Delete",
    deleteOrder: "Delete order",
    dismissInstallPrompt: "Dismiss install prompt",
    discount: "Discount",
    dishesCount: "{count} dishes",
    edit: "Edit",
    editMenuItem: "Edit Menu Item",
    editPromoCode: "Edit Promo Code",
    editTable: "Edit Table",
    enable: "Enable",
    disable: "Disable",
    downloadReceipt: "Download receipt",
    each: "each",
    englishSound: "English sound",
    enterPromoCode: "Enter a promo code.",
    expiresIn: "Expires in",
    expirationMinutes: "Expiration minutes",
    failedConfirmPayment: "Failed to confirm payment.",
    fixedUsdDiscount: "Fixed USD discount",
    fiveToTenMinutes: "5-10 min",
    fiveToTenUsd: "$5-$10",
    free: "Free",
    from: "From",
    fullDescription: "Full description",
    hideDetail: "Hide detail",
    hideDetails: "Hide Details",
    hideFullDescription: "Hide full description",
    hidden: "Hidden",
    imageUrl: "Image URL",
    imageTooLarge: "Image must be 5MB or smaller.",
    imagePreview: "Image preview",
    inactive: "Inactive",
    increase: "Increase",
    install: "Install",
    installHappyBoat: "Install HappyBoat",
    installedHappyBoat: "HappyBoat installed",
    installPhonePrompt: "Add it to your phone for a faster app experience.",
    installIosPrompt: "On iPhone, tap Share, then Add to Home Screen.",
    invalidImageType: "Only PNG, JPG, WebP, and GIF images are allowed.",
    invalidOtp: "Invalid OTP",
    invalidPromo: "Promo code is invalid.",
    kitchen: "Kitchen",
    kitchenAcceptMode: "Accept mode",
    kitchenPaidItems: "Paid items grouped for preparation",
    khmerSound: "Khmer sound",
    languageButton: "ខ្មែរ",
    label: "Label",
    live: "Live",
    liveOrders: "Live Orders",
    liveRestaurantOps: "Live restaurant operations",
    loginSuccess: "Logged in successfully.",
    logout: "Logout",
    loadingAnalytics: "Loading analytics...",
    loadingMenu: "Loading menu...",
    maxDiscountUsd: "Max discount USD",
    manualMode: "Manual",
    manualKitchenHint: "Staff accept each paid item manually.",
    manageCategories: "Manage Categories",
    merchantAccountId: "Merchant account ID",
    merchantCity: "Merchant city",
    merchantDetailsLoadFailed: "Merchant details failed to load.",
    merchantDetailsUpdateFailed: "Merchant details update failed.",
    merchantDetailsUpdated: "Merchant details updated.",
    merchantName: "Merchant name",
    menu: "Menu",
    name: "Name",
    minutesAgo: "{minutes}min ago",
    menuItemCreated: "Menu item created.",
    menuItemSaveFailed: "Menu item save failed.",
    menuItemUpdated: "Menu item updated.",
    new: "New",
    newMenuItem: "New Menu Item",
    newOrderUpdate: "New order update",
    next: "Next",
    newPromoCode: "New Promo Code",
    newTable: "New Table",
    noKitchenItems: "No paid kitchen items are waiting.",
    noDishes: "No dishes match your filters",
    noCategoriesYet: "No categories yet.",
    noOrdersFilter: "No orders match the current filter.",
    noDescription: "No description",
    noAddonsYet: "No add-ons yet.",
    noSizeLevelsYet: "No size levels yet.",
    noPromoCodes: "No promo codes yet.",
    noAccounts: "No accounts yet.",
    noCallStaffRequests: "No open call staff requests.",
    note: "Note",
    openReceipt: "Open receipt",
    opened: "Opened",
    order: "Order",
    orderCancelled: "Order cancelled. You can delete it from this device.",
    orderDeleted: "Order deleted from this device.",
    orderDetail: "Order Detail",
    orderNeedsAttention: "Order needs attention",
    orderStatus: "Order status",
    orders: "Orders",
    orderPlacedChooseBank: "Order placed! Choose how to pay.",
    orderPlacedQr: "Order placed! Scan the KHQR code below to pay.",
    orderPlacedTapPay: "Order placed. Tap 'Pay with Bakong KHQR' to generate a QR code.",
    orderComplete: "Complete",
    orderStatusUpdated: "Order status updated",
    payments: "Payments",
    payWithBakong: "Pay with Bakong KHQR",
    paymentConfirmed: "Payment confirmed - order sent to kitchen",
    paidOrderReady: "Paid order ready",
    paymentExpired: "Payment expired",
    paymentCancelFailed: "Could not cancel payment.",
    paymentCancelled: "Payment cancelled.",
    paymentCheckFailed: "Could not check payment status.",
    paymentAlreadyPaid: "This payment is already PAID. Telegram will not be duplicated.",
    paymentMarkedPaid: "Payment marked as PAID and Telegram notification was triggered.",
    percentDiscount: "Percent discount",
    paidMinutes: "Paid",
    paymentReceived: "Payment received. Your order has been sent to staff.",
    placeOrder: "Place Order",
    placingOrder: "Placing order...",
    paidPayments: "paid payments",
    paidRevenueByDay: "Paid revenue by day",
    polling: "Polling",
    paymentBreakdown: "Payment breakdown",
    paymentIssues: "Payment issues",
    paymentAutoCheckHint: "We keep checking payment status automatically while this QR is open.",
    print: "Print",
    peakDay: "Peak day",
    peakHours: "Peak hours",
    promos: "Promos",
    promoCodes: "Promo Codes",
    promoCodeUpdated: "Promo code updated.",
    promoCodeCreated: "Promo code created.",
    promoApplied: "Promo code applied.",
    promoBeforeItems: "Add items before applying a promo code.",
    promoCode: "Promo code",
    quantity: "Quantity",
    qty: "qty",
    qrExpired: "QR has expired. Close and request a new one.",
    qrExpiredShort: "QR expired. Generate a new one below or cancel the payment.",
    qrImageSaved: "QR image saved.",
    readyForPickup: "Ready",
    recentOrders: "Recent orders",
    receivedByStaff: "Received",
    receivedOrderVoice: "Received Order",
    receivedPaymentVoice: "Received Payment",
    recordedVoice: "MP3",
    receipt: "Receipt",
    rejected: "Rejected",
    refresh: "Refresh",
    refreshPaymentNow: "Refresh now",
    refreshLatestApp: "Refresh to use the latest HappyBoat app.",
    removeItem: "Remove item",
    resendIn: "Resend in {seconds}s",
    resendOtp: "Resend OTP",
    resolve: "Resolve",
    resolveFailed: "Could not resolve request.",
    resolved: "Resolved",
    revenueByTable: "Revenue by Table",
    reference: "Reference",
    required: "Required",
    saveImage: "Save image",
    save: "Save",
    saving: "Saving...",
    search: "Search",
    searchOrderTable: "Search order # or table",
    selectOrderDetail: "Select an order to see its details.",
    selectPayment: "Select a payment.",
    sendOtp: "Send OTP",
    sending: "Sending...",
    superAdmin: "SuperAdmin",
    scanToPay: "Scan to pay",
    scanQrCode: "Scan QR Code",
    scanQrHelp: "Scan the QR with Bakong or another KHQR app, then wait for confirmation.",
    searchDishes: "Search dishes...",
    showDetail: "Show detail",
    showFullDescription: "Show full description",
    signInFailed: "Sign in failed",
    signIn: "Sign in",
    serverVoice: "Server",
    otpSubtitle: "Enter the 6-digit code sent to {email}.",
    otpExpiredRequestNew: "OTP expired. Please request a new OTP.",
    otpSendFailed: "Could not send OTP.",
    otpSent: "OTP sent.",
    sortBy: "Sort by",
    soundLanguage: "Sound language",
    sortNewest: "Newest first",
    sortOldest: "Oldest first",
    sortPayment: "Payment status",
    sortStatus: "Order status",
    sortCategory: "Category",
    sortItemName: "Item name",
    sortTable: "Table",
    sortOrderNo: "Order #",
    specialInstructions: "Special instructions",
    size: "Size",
    sizeLevels: "Size Levels",
    subtotal: "Subtotal",
    table: "Table",
    tableLabel: "Table",
    tables: "Tables",
    tagsLabel: "Tags",
    testOrderSound: "Test order sound",
    today: "Today",
    threeToFiveUsd: "$3-$5",
    to: "To",
    toggle: "Toggle",
    topItems: "Top Items",
    total: "Total",
    totalQuantityLabel: "Total:",
    totalMinutes: "Total",
    transactionLog: "Transaction Log",
    transaction: "Transaction",
    tenToTwentyMinutes: "10-20 min",
    tenUsdPlus: "$10+",
    twentyPlusMinutes: "20+ min",
    underFiveMinutes: "Under 5 min",
    underThreeUsd: "Under $3",
    paid: "Paid",
    pending: "Pending",
    expired: "Expired",
    unpaid: "UNPAID",
    updated: "Updated",
    update: "Update",
    updateAvailable: "Update available",
    unpaidNoQr: "Unpaid (no QR)",
    unavailable: "Unavailable",
    unavailableItems: "Unavailable items",
    uploadImage: "Upload image",
    uploadFailed: "Image upload failed.",
    username: "Username",
    password: "Password",
    verify: "Verify",
    verificationCode: "Verification code",
    verifyIdentityMerchant: "Please verify your identity to change merchant details.",
    verifyOtp: "Verify OTP",
    viewCart: "View cart",
    viewDetails: "View Details",
    viewOrder: "View order",
    viewFullImage: "View full image",
    viewPayment: "View payment",
    viewPaymentQr: "View payment QR",
    expiredQrHelp: "If you already paid, refresh once. If not, generate a new QR and pay with the new code.",
    waitingTooLong: "Paid order waiting more than 10 minutes",
    weeklyRevenue: "Weekly Revenue",
    highlights: "Highlights",
    itemsSold: "items sold",
    lastDay: "Last day",
    ordersByItem: "Orders by item",
    paidCount: "paid",
    paymentReceivedAlert: "Received payment",
    preparing: "Preparing",
    welcomeTitle: "Welcome to HappyBoat",
    operationsHome: "Home",
    operationsOverview: "Operations overview",
    openRequests: "Open requests",
    youAreAtTable: "You are at table",
    yourOrder: "Your Order"
  },
  km: {
    addToCart: "បន្ថែមទៅកន្ត្រក",
    add: "បន្ថែម",
    addNewMenu: "បន្ថែមម្ហូបថ្មី",
    addDishes: "បន្ថែមម្ហូបដើម្បីចាប់ផ្តើម",
    addedToCart: "បានបន្ថែមទៅកន្ត្រក។",
    addedToCartTitle: "បានបន្ថែមទៅកន្ត្រក",
    addExtras: "បន្ថែមជម្រើស",
    accept: "ទទួល",
    acceptAll: "ទទួលទាំងអស់",
    acceptedPreparing: "បានទទួល",
    addons: "បន្ថែម",
    allPrices: "គ្រប់តម្លៃ",
    allPayments: "ការទូទាត់ទាំងអស់",
    allCategories: "គ្រប់ប្រភេទ",
    allDates: "គ្រប់ថ្ងៃ",
    allStatuses: "គ្រប់ស្ថានភាព",
    allTimes: "គ្រប់ពេល",
    alert: "ជូនដំណឹង",
    alertStaff: "ជូនដំណឹងបុគ្គលិក",
    amountToPay: "ចំនួនត្រូវបង់",
    analytics: "វិភាគ",
    analyticsLoadFailed: "ផ្ទុកវិភាគមិនបាន",
    accounts: "គណនី",
    accountDeactivated: "បានបិទគណនី",
    accountDeactivateFailed: "បិទគណនីមិនបាន",
    accountCreateFailed: "បង្កើតគណនីមិនបាន",
    accountLoadFailed: "ផ្ទុកគណនីមិនបាន",
    appLanguage: "ភាសាកម្មវិធី",
    active: "កំពុងដំណើរការ",
    activeOrders: "ការកម្មង់កំពុងដំណើរការ",
    accessToken: "Access token",
    admin: "អ្នកគ្រប់គ្រង",
    adminAccountCreated: "បានបង្កើតគណនីអ្នកគ្រប់គ្រង",
    adminAccounts: "គណនីអ្នកគ្រប់គ្រង",
    awaitingPayment: "បង់ប្រាក់",
    averageOrder: "ការកម្មង់មធ្យម",
    apply: "ប្រើ",
    available: "មាន",
    autoAcceptOn: "ទទួលដោយស្វ័យប្រវត្តិ",
    autoAcceptKitchenHint: "ម្ហូបបានបង់ប្រាក់ថ្មីនឹងត្រូវបានទទួលដោយស្វ័យប្រវត្តិ។",
    back: "ត្រឡប់ក្រោយ",
    cancel: "បោះបង់",
    cancelled: "បានបោះបង់",
    cancelPayment: "បោះបង់ការទូទាត់",
    cartItemCount: "ម្ហូប {count}",
    capacity: "ចំនួនកៅអី",
    callStaff: "ហៅបុគ្គលិក",
    callingStaff: "កំពុងហៅ...",
    callStaffAlreadySent: "បុគ្គលិកកំពុងមកហើយ។",
    callStaffFailed: "មិនអាចហៅបុគ្គលិកបាន។",
    callStaffRequests: "សំណើហៅបុគ្គលិក",
    callStaffSent: "បានហៅបុគ្គលិក។",
    callStaffSentShort: "បានហៅបុគ្គលិក",
    category: "ប្រភេទ",
    categories: "ប្រភេទ",
    categoryCreated: "បានបង្កើតប្រភេទ។",
    categoryDeleted: "បានលុបប្រភេទ។",
    categoryDeleteFailed: "លុបប្រភេទមិនបាន",
    categoryHasItems: "អាចលុបបានតែបន្ទាប់ពីផ្លាស់ទី ឬលុបម្ហូបក្នុងប្រភេទនេះ។",
    categoryItemCount: "ម្ហូប {count}",
    categoryName: "ឈ្មោះប្រភេទ",
    categoryOrder: "លំដាប់",
    categorySaveFailed: "រក្សាទុកប្រភេទមិនបាន",
    categorySlug: "ស្លាក់",
    categoryUpdated: "បានកែប្រភេទ។",
    changeLanguage: "ប្តូរភាសា",
    changeMerchantDetails: "កែព័ត៌មានអាជីវករ",
    checkYourEmail: "សូមពិនិត្យអ៊ីមែល",
    checkPaymentStatus: "ពិនិត្យការទូទាត់",
    generateNewQr: "បង្កើត QR ថ្មី",
    checking: "កំពុងពិនិត្យ",
    checkingPayment: "កំពុងពិនិត្យការទូទាត់...",
    checkingPromoCode: "កំពុងពិនិត្យកូដប្រូម៉ូសិន...",
    chooseSizeLevel: "ជ្រើសទំហំ",
    bakongAccessToken: "Bakong access token",
    bakongEmail: "អ៊ីមែល Bakong",
    bakongPaymentSettings: "ការកំណត់ការទូទាត់ Bakong សម្រាប់ QR ថ្មី។",
    beepOnly: "សំឡេងប៊ីបប៉ុណ្ណោះ",
    browserVoice: "ឧបករណ៍",
    clearFilters: "សម្អាតតម្រង",
    complete: "បញ្ចប់",
    completeAll: "បញ្ចប់ទាំងអស់",
    completed: "បានបញ្ចប់",
    confirmAcceptAll: "ទទួលម្ហូប {item} ចំនួន {count}?",
    confirmCompleteAll: "បញ្ចប់ម្ហូប {item} ដែលបានទទួល ចំនួន {count}?",
    confirmCancelOrder: "បោះបង់ការកម្មង់នេះ?",
    confirmCancelPayment: "បោះបង់ការទូទាត់នេះ? ការកម្មង់នឹងត្រូវបានបោះបង់លើឧបករណ៍នេះ។",
    confirmDeleteCategory: "លុបប្រភេទនេះ?",
    confirmPaid: "ខ្ញុំបានទទួលប្រាក់ Bakong រួចហើយ",
    confirmPaymentPrompt: "បញ្ជាក់ថាការទូទាត់នេះបានបង់ហើយ? ប្រើតែពេលអ្នកបានទទួលប្រាក់ Bakong រួចប៉ុណ្ណោះ។",
    confirming: "កំពុងបញ្ជាក់...",
    create: "បង្កើត",
    createAdmin: "បង្កើតអ្នកគ្រប់គ្រង",
    codeExpiresIn: "លេខកូដផុតកំណត់ក្នុង {time}",
    confirmDeactivateAccount: "បិទគណនី {username}?",
    customerAlertFailed: "មិនអាចជូនដំណឹងបុគ្គលិកបាន។",
    customerAlertSent: "បានជូនដំណឹងបុគ្គលិក។",
    customerAlertSentShort: "បានជូនដំណឹង",
    customerWaitingVoice: "អតិថិជនរង់ចាំដប់នាទីហើយ",
    dailyRevenue: "ចំណូលថ្ងៃនេះ",
    dashboardTitle: "ផ្ទាំងគ្រប់គ្រង HappyBoat",
    dashboardSubtitle: "សម្រាប់ SuperAdmin និង Admin",
    close: "បិទ",
    closeCart: "បិទកន្ត្រក",
    dashboard: "ផ្ទាំងគ្រប់គ្រង",
    defaultLabel: "លំនាំដើម",
    defaultCurrency: "រូបិយប័ណ្ណលំនាំដើម",
    decrease: "បន្ថយ",
    deactivate: "បិទដំណើរការ",
    deleteCategory: "លុប",
    deleteOrder: "លុបការកម្មង់",
    dismissInstallPrompt: "បិទសារណែនាំដំឡើង",
    discount: "បញ្ចុះតម្លៃ",
    dishesCount: "ម្ហូប {count}",
    edit: "កែ",
    editMenuItem: "កែម្ហូប",
    editPromoCode: "កែកូដប្រូម៉ូសិន",
    editTable: "កែតុ",
    enable: "បើក",
    disable: "បិទ",
    downloadReceipt: "ទាញយកវិក្កយបត្រ",
    each: "ក្នុងមួយ",
    englishSound: "សំឡេងអង់គ្លេស",
    enterPromoCode: "សូមបញ្ចូលកូដប្រូម៉ូសិន។",
    expiresIn: "ផុតកំណត់ក្នុង",
    expirationMinutes: "នាទីផុតកំណត់",
    failedConfirmPayment: "បញ្ជាក់ការទូទាត់មិនបាន។",
    fixedUsdDiscount: "បញ្ចុះតម្លៃជាដុល្លារ",
    fiveToTenMinutes: "៥-១០ នាទី",
    fiveToTenUsd: "$5-$10",
    free: "ឥតគិតថ្លៃ",
    from: "ចាប់ពី",
    fullDescription: "ការពិពណ៌នាពេញ",
    hideDetail: "លាក់លម្អិត",
    hideDetails: "លាក់លម្អិត",
    hideFullDescription: "លាក់ការពិពណ៌នាពេញ",
    hidden: "លាក់",
    imageUrl: "URL រូបភាព",
    imageTooLarge: "រូបភាពត្រូវមានទំហំ ៥MB ឬតូចជាងនេះ។",
    imagePreview: "មើលរូបភាពជាមុន",
    inactive: "អសកម្ម",
    increase: "បន្ថែម",
    install: "ដំឡើង",
    installHappyBoat: "ដំឡើង HappyBoat",
    installedHappyBoat: "បានដំឡើង HappyBoat",
    installPhonePrompt: "បន្ថែមទៅទូរស័ព្ទរបស់អ្នក ដើម្បីប្រើកម្មវិធីបានលឿនជាងមុន។",
    installIosPrompt: "លើ iPhone សូមចុច Share បន្ទាប់មក Add to Home Screen។",
    invalidImageType: "អនុញ្ញាតតែរូបភាព PNG, JPG, WebP និង GIF ប៉ុណ្ណោះ។",
    invalidOtp: "OTP មិនត្រឹមត្រូវ",
    invalidPromo: "កូដប្រូម៉ូសិនមិនត្រឹមត្រូវ។",
    kitchen: "ផ្ទះបាយ",
    kitchenAcceptMode: "របៀបទទួល",
    kitchenPaidItems: "ម្ហូបបានបង់ប្រាក់ សម្រាប់រៀបចំ",
    khmerSound: "សំឡេងខ្មែរ",
    languageButton: "English",
    label: "ស្លាក",
    live: "ផ្ទាល់",
    liveOrders: "ការកម្មង់ផ្ទាល់",
    liveRestaurantOps: "ប្រតិបត្តិការហាងអាហារផ្ទាល់",
    loginSuccess: "បានចូលប្រើដោយជោគជ័យ។",
    logout: "ចាកចេញ",
    loadingAnalytics: "កំពុងផ្ទុកវិភាគ...",
    loadingMenu: "កំពុងផ្ទុកម៉ឺនុយ...",
    maxDiscountUsd: "បញ្ចុះតម្លៃអតិបរមា USD",
    manualMode: "ដោយដៃ",
    manualKitchenHint: "បុគ្គលិកទទួលម្ហូបបានបង់ប្រាក់ម្តងមួយៗដោយដៃ។",
    manageCategories: "គ្រប់គ្រងប្រភេទ",
    merchantAccountId: "លេខគណនីអាជីវករ",
    merchantCity: "ទីក្រុងអាជីវករ",
    merchantDetailsLoadFailed: "ផ្ទុកព័ត៌មានអាជីវករមិនបាន។",
    merchantDetailsUpdateFailed: "អាប់ដេតព័ត៌មានអាជីវករមិនបាន។",
    merchantDetailsUpdated: "បានអាប់ដេតព័ត៌មានអាជីវករ។",
    merchantName: "ឈ្មោះអាជីវករ",
    menu: "ម៉ឺនុយ",
    name: "ឈ្មោះ",
    minutesAgo: "{minutes} នាទីមុន",
    menuItemCreated: "បានបង្កើតម្ហូប។",
    menuItemSaveFailed: "រក្សាទុកម្ហូបមិនបាន។",
    menuItemUpdated: "បានកែម្ហូប។",
    new: "ថ្មី",
    newMenuItem: "ម្ហូបថ្មី",
    newOrderUpdate: "ការកម្មង់ថ្មី",
    next: "បន្ទាប់",
    newPromoCode: "កូដប្រូម៉ូសិនថ្មី",
    newTable: "តុថ្មី",
    noKitchenItems: "មិនមានម្ហូបផ្ទះបាយកំពុងរង់ចាំទេ។",
    noDishes: "មិនមានម្ហូបត្រូវនឹងតម្រងទេ",
    noCategoriesYet: "មិនទាន់មានប្រភេទទេ។",
    noOrdersFilter: "មិនមានការកម្មង់ត្រូវនឹងតម្រងទេ។",
    noDescription: "មិនមានការពិពណ៌នា",
    noAddonsYet: "មិនទាន់មានជម្រើសបន្ថែមទេ។",
    noSizeLevelsYet: "មិនទាន់មានទំហំទេ។",
    noPromoCodes: "មិនទាន់មានកូដប្រូម៉ូសិនទេ។",
    noAccounts: "មិនទាន់មានគណនីទេ។",
    noCallStaffRequests: "មិនមានសំណើហៅបុគ្គលិកទេ។",
    note: "ចំណាំ",
    openReceipt: "បើកវិក្កយបត្រ",
    opened: "បានបើក",
    order: "ការកម្មង់",
    orderCancelled: "ការកម្មង់ត្រូវបានបោះបង់។ អ្នកអាចលុបវាពីឧបករណ៍នេះ។",
    orderDeleted: "បានលុបការកម្មង់ពីឧបករណ៍នេះ។",
    orderDetail: "លម្អិតការកម្មង់",
    orderNeedsAttention: "ការកម្មង់ត្រូវការយកចិត្តទុកដាក់",
    orderStatus: "ស្ថានភាពកម្មង់",
    orders: "ការកម្មង់",
    orderPlacedChooseBank: "បានដាក់ការកម្មង់! សូមជ្រើសវិធីបង់ប្រាក់។",
    orderPlacedQr: "បានដាក់ការកម្មង់! ស្កេន KHQR ខាងក្រោមដើម្បីបង់ប្រាក់។",
    orderPlacedTapPay: "បានដាក់ការកម្មង់។ ចុច 'បង់តាម Bakong KHQR' ដើម្បីបង្កើត QR។",
    orderComplete: "រួចរាល់",
    orderStatusUpdated: "ស្ថានភាពកម្មង់បានអាប់ដេត",
    payments: "ការទូទាត់",
    payWithBakong: "បង់តាម Bakong KHQR",
    paymentConfirmed: "បានបញ្ជាក់ការទូទាត់ - បានផ្ញើទៅផ្ទះបាយ",
    paidOrderReady: "ការកម្មង់បានបង់ រួចរាល់សម្រាប់រៀបចំ",
    paymentExpired: "ការទូទាត់ផុតកំណត់",
    paymentCancelFailed: "មិនអាចបោះបង់ការទូទាត់បាន។",
    paymentCancelled: "បានបោះបង់ការទូទាត់។",
    paymentCheckFailed: "មិនអាចពិនិត្យស្ថានភាពទូទាត់បាន។",
    paymentAlreadyPaid: "ការទូទាត់នេះបានបង់រួចហើយ។ Telegram នឹងមិនផ្ញើម្តងទៀតទេ។",
    paymentMarkedPaid: "បានសម្គាល់ថាបានបង់ ហើយបានផ្ញើ Telegram។",
    percentDiscount: "បញ្ចុះតម្លៃជាភាគរយ",
    paidMinutes: "បានបង់",
    paymentReceived: "បានទទួលការទូទាត់។ ការកម្មង់របស់អ្នកបានផ្ញើទៅបុគ្គលិក។",
    placeOrder: "ដាក់ការកម្មង់",
    placingOrder: "កំពុងដាក់ការកម្មង់...",
    paidPayments: "ការទូទាត់បានបង់",
    paidRevenueByDay: "ចំណូលបានបង់តាមថ្ងៃ",
    polling: "កំពុងទាញទិន្នន័យ",
    paymentBreakdown: "បែងចែកការទូទាត់",
    paymentIssues: "បញ្ហាទូទាត់",
    paymentAutoCheckHint: "ប្រព័ន្ធនឹងពិនិត្យស្ថានភាពទូទាត់ដោយស្វ័យប្រវត្តិ ខណៈ QR នេះកំពុងបើក។",
    print: "បោះពុម្ព",
    peakDay: "ថ្ងៃខ្ពស់បំផុត",
    peakHours: "ម៉ោងមមាញឹក",
    promos: "ប្រូម៉ូសិន",
    promoCodes: "កូដប្រូម៉ូសិន",
    promoCodeUpdated: "បានកែកូដប្រូម៉ូសិន។",
    promoCodeCreated: "បានបង្កើតកូដប្រូម៉ូសិន។",
    promoApplied: "បានប្រើកូដប្រូម៉ូសិន។",
    promoBeforeItems: "សូមបន្ថែមម្ហូបមុនប្រើកូដប្រូម៉ូសិន។",
    promoCode: "កូដប្រូម៉ូសិន",
    quantity: "ចំនួន",
    qty: "ចំនួន",
    qrExpired: "QR ផុតកំណត់។ បិទហើយស្នើ QR ថ្មី។",
    qrExpiredShort: "QR ផុតកំណត់។ បង្កើតថ្មីខាងក្រោម ឬបោះបង់ការទូទាត់។",
    qrImageSaved: "បានរក្សាទុករូបភាព QR។",
    readyForPickup: "រួចរាល់",
    recentOrders: "ការកម្មង់ថ្មីៗ",
    receivedByStaff: "បានទទួល",
    receivedOrderVoice: "បានទទួលការកម្មង់",
    receivedPaymentVoice: "បានទទួលការទូទាត់",
    recordedVoice: "MP3",
    receipt: "វិក្កយបត្រ",
    rejected: "បានបដិសេធ",
    refresh: "ផ្ទុកឡើងវិញ",
    refreshPaymentNow: "ពិនិត្យឥឡូវ",
    refreshLatestApp: "ផ្ទុកឡើងវិញ ដើម្បីប្រើកម្មវិធី HappyBoat ថ្មីបំផុត។",
    removeItem: "លុបម្ហូប",
    resendIn: "ផ្ញើម្ដងទៀតក្នុង {seconds}s",
    resendOtp: "ផ្ញើ OTP ម្ដងទៀត",
    resolve: "ដោះស្រាយ",
    resolveFailed: "មិនអាចដោះស្រាយសំណើបាន។",
    resolved: "បានដោះស្រាយ",
    revenueByTable: "ចំណូលតាមតុ",
    reference: "លេខយោង",
    required: "ត្រូវការ",
    saveImage: "រក្សាទុករូបភាព",
    save: "រក្សាទុក",
    saving: "កំពុងរក្សាទុក...",
    search: "ស្វែងរក",
    searchOrderTable: "ស្វែងរកលេខកម្មង់ ឬតុ",
    selectOrderDetail: "ជ្រើសការកម្មង់ដើម្បីមើលលម្អិត។",
    selectPayment: "ជ្រើសការទូទាត់។",
    sendOtp: "ផ្ញើ OTP",
    sending: "កំពុងផ្ញើ...",
    superAdmin: "អ្នកគ្រប់គ្រងកំពូល",
    scanToPay: "ស្កេនដើម្បីបង់ប្រាក់",
    scanQrCode: "ស្កេន QR Code",
    scanQrHelp: "ស្កេន QR ដោយ Bakong ឬកម្មវិធី KHQR ផ្សេងទៀត បន្ទាប់មករង់ចាំការបញ្ជាក់។",
    searchDishes: "ស្វែងរកម្ហូប...",
    showDetail: "បង្ហាញលម្អិត",
    showFullDescription: "បង្ហាញការពិពណ៌នាពេញ",
    signInFailed: "ចូលប្រើមិនបាន",
    signIn: "ចូលប្រើ",
    serverVoice: "ម៉ាស៊ីនមេ",
    otpSubtitle: "បញ្ចូលលេខកូដ ៦ ខ្ទង់ ដែលបានផ្ញើទៅ {email}។",
    otpExpiredRequestNew: "OTP ផុតកំណត់។ សូមស្នើ OTP ថ្មី។",
    otpSendFailed: "មិនអាចផ្ញើ OTP បាន។",
    otpSent: "បានផ្ញើ OTP។",
    sortBy: "តម្រៀបតាម",
    soundLanguage: "ភាសាសំឡេង",
    sortNewest: "ថ្មីមុន",
    sortOldest: "ចាស់មុន",
    sortPayment: "ស្ថានភាពទូទាត់",
    sortStatus: "ស្ថានភាពកម្មង់",
    sortCategory: "ប្រភេទ",
    sortItemName: "ឈ្មោះម្ហូប",
    sortTable: "តុ",
    sortOrderNo: "លេខកម្មង់",
    specialInstructions: "សំណូមពរពិសេស",
    size: "ទំហំ",
    sizeLevels: "ទំហំ",
    subtotal: "សរុបរង",
    table: "តុ",
    tableLabel: "តុ",
    tables: "តុ",
    tagsLabel: "ស្លាក",
    testOrderSound: "សាកសំឡេងកម្មង់",
    today: "ថ្ងៃនេះ",
    threeToFiveUsd: "$3-$5",
    to: "ដល់",
    toggle: "បើក/បិទ",
    topItems: "ម្ហូបលក់ដាច់",
    total: "សរុប",
    totalQuantityLabel: "សរុប:",
    totalMinutes: "នាទីសរុប",
    transactionLog: "កំណត់ត្រាប្រតិបត្តិការ",
    transaction: "ប្រតិបត្តិការ",
    tenToTwentyMinutes: "១០-២០ នាទី",
    tenUsdPlus: "$10+",
    twentyPlusMinutes: "២០+ នាទី",
    underFiveMinutes: "ក្រោម ៥ នាទី",
    underThreeUsd: "ក្រោម $3",
    paid: "បានបង់",
    pending: "កំពុងរង់ចាំ",
    expired: "ផុតកំណត់",
    unpaid: "មិនទាន់បង់",
    updated: "បានអាប់ដេត",
    update: "អាប់ដេត",
    updateAvailable: "មានអាប់ដេតថ្មី",
    unpaidNoQr: "មិនទាន់បង់ (គ្មាន QR)",
    unavailable: "មិនមាន",
    unavailableItems: "ម្ហូបមិនមាន",
    uploadImage: "បង្ហោះរូបភាព",
    uploadFailed: "បង្ហោះរូបភាពមិនបាន។",
    username: "ឈ្មោះអ្នកប្រើ",
    password: "ពាក្យសម្ងាត់",
    verify: "ផ្ទៀងផ្ទាត់",
    verificationCode: "លេខកូដផ្ទៀងផ្ទាត់",
    verifyIdentityMerchant: "សូមផ្ទៀងផ្ទាត់អត្តសញ្ញាណ ដើម្បីកែព័ត៌មានអាជីវករ។",
    verifyOtp: "ផ្ទៀងផ្ទាត់ OTP",
    viewCart: "មើលកន្ត្រក",
    viewDetails: "មើលលម្អិត",
    viewOrder: "មើលការកម្មង់",
    viewFullImage: "មើលរូបភាពពេញ",
    viewPayment: "មើលការទូទាត់",
    viewPaymentQr: "មើល QR ទូទាត់",
    expiredQrHelp: "បើអ្នកបានបង់រួច សូមពិនិត្យម្តងទៀត។ បើមិនទាន់បង់ សូមបង្កើត QR ថ្មី ហើយបង់តាមកូដថ្មី។",
    waitingTooLong: "ការកម្មង់បានបង់ រង់ចាំលើស ១០ នាទី",
    weeklyRevenue: "ចំណូលសប្តាហ៍នេះ",
    highlights: "ចំណុចសំខាន់",
    itemsSold: "ចំនួនបានលក់",
    lastDay: "ថ្ងៃចុងក្រោយ",
    ordersByItem: "ការកម្មង់តាមម្ហូប",
    paidCount: "បានបង់",
    paymentReceivedAlert: "បានទទួលការទូទាត់",
    preparing: "កំពុងរៀបចំ",
    welcomeTitle: "សូមស្វាគមន៍មកកាន់ HappyBoat",
    operationsHome: "ទំព័រដើម",
    operationsOverview: "សង្ខេបប្រតិបត្តិការ",
    openRequests: "សំណើបើក",
    youAreAtTable: "អ្នកនៅតុលេខ",
    yourOrder: "ការកម្មង់របស់អ្នក"
  }
};

const LanguageContext = createContext({
  language: "en",
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key) => key
});

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState("en");

  useEffect(() => {
    const stored = window.localStorage.getItem(STORAGE_KEY);
    if (stored === "km" || stored === "en") {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = useCallback((nextLanguage) => {
    setLanguageState(nextLanguage);
    window.localStorage.setItem(STORAGE_KEY, nextLanguage);
    document.documentElement.lang = nextLanguage === "km" ? "km" : "en";
  }, []);

  const toggleLanguage = useCallback(() => {
    setLanguage(language === "km" ? "en" : "km");
  }, [language, setLanguage]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    toggleLanguage,
    t: (key) => DICTIONARY[language]?.[key] || DICTIONARY.en[key] || key
  }), [language, setLanguage, toggleLanguage]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export function LanguageToggle({ className }) {
  const { language, setLanguage, t } = useLanguage();
  const currentLanguage = LANGUAGE_OPTIONS.find((option) => option.value === language) || LANGUAGE_OPTIONS[0];

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          type="button"
          variant="outline"
          className={cn("min-h-10 rounded-xl px-3 text-xs", className)}
          aria-label={t("changeLanguage")}
        >
          <Languages className="h-4 w-4" />
          <span className="font-bold leading-none">{currentLanguage.label}</span>
          <ChevronDown className="h-3.5 w-3.5 text-muted-foreground" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        {LANGUAGE_OPTIONS.map((option) => (
          <DropdownMenuItem key={option.value} onSelect={() => setLanguage(option.value)}>
            <span className="flex h-4 w-4 items-center justify-center">
              {language === option.value ? <Check className="h-4 w-4" /> : null}
            </span>
            <span className="font-medium">{option.label}</span>
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
